[service_providers.google.env_vars.GOOGLE_APPLICATION_CREDENTIALS]
type = "string"
required = false
examples = ["/path/to/credentials.json"]
description = """\
The [GCP api key][urls.gcp_authentication_api_key] used for authentication.\
"""

[service_providers.google.options.api_key]
type = "string"
required = true
examples = ["AtvF23duxxmfFndnwvpegkbmfcjgvjabpg"]
relevant_when = {credentials_path = ""}
description = """\
The [GCP api key][urls.gcp_authentication_api_key] used for authentication.\
"""

[service_providers.google.options.credentials_path]
type = "string"
required = true
examples = ["/path/to/credentials.json"]
relevant_when = {api_key = ""}
description = """\
The filename for a Google Cloud service account credentials JSON file \
used to authenticate access to the stackdriver logging API.\
"""