paths:
  "Cargo.lock":
    - Did you review changed dependencies for security concerns?
    - Has at least one other team member approved the dependency changes?
  "rfcs/**":
    - Have at least 3 team members approved this RFC?
  "src/**":
    - Did you add adequate behavior tests (`tests/behavior`)? Specifically, nested fields support.
    - Did you add adequate logging? Note: we support rate-limited logging for the hot path.
    - Did you add adequate documentation?
