# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "rust:cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "hoverbear"
    assigness:
      - "hoverbear"
    labels:
      - "domain: deps"
    commit-message:
      prefix: "chore(deps)"
