[sinks.aws_s3]
title = "AWS S3"
batch_is_common = true
batch_max_size = 10490000
batch_timeout_secs = 300
beta = true
buffer = true
common = true
delivery_guarantee = "at_least_once"
egress_method = "batching"
encodings = ["ndjson", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
request_rate_limit_duration_secs = 1
request_rate_limit_num =5
request_retry_attempts = 5
request_retry_initial_backoff_secs = 1
request_retry_max_duration_secs = 10
request_in_flight_limit = 5
request_timeout_secs = 30
service_limits_short_link = "aws_s3_service_limits"
service_providers = ["AWS"]
write_to_description = "[Amazon Web Service's S3 service][urls.aws_s3] via the [`PutObject` API endpoint](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)"

[sinks.aws_s3.options.bucket]
type = "string"
common = true
examples = ["my-bucket"]
required = true
description = "The S3 bucket name. Do not include a leading `s3://` or a trailing `/`."

[sinks.aws_s3.options.filename_append_uuid]
type = "bool"
category = "Object Names"
default = true
required = true
description = "Whether or not to append a UUID v4 token to the end of the file. This ensures there are no name collisions high volume use cases."

[sinks.aws_s3.options.filename_extension]
type = "string"
category = "Object Names"
default = "log"
required = true
description = "The extension to use in the object name."

[sinks.aws_s3.options.compression]
type = "string"
common = true
required = true
description = "The compression mechanism to use."

[sinks.aws_s3.options.compression.enum]
gzip = "GZIP compression"
none = "No compression"

[sinks.aws_s3.options.filename_time_format]
type = "string"
category = "Object Names"
default = "%s"
required = true
description = "The format of the resulting object file name. [`strftime` specifiers][urls.strptime_specifiers] are supported."

[sinks.aws_s3.options.key_prefix]
type = "string"
category = "Object Names"
common = true
default = "date=%F/"
examples = [
  "date=%F/",
  "date=%F/hour=%H/",
  "year=%Y/month=%m/day=%d/",
  "application_id={{ application_id }}/date=%F/",
]
partition_key = true
templateable = true
description = "A prefix to apply to all object key names. This should be used to partition your objects, and it's important to end this value with a `/` if you want this to be the root S3 \"folder\"."

[sinks.aws_s3.options.acl]
type = "string"
category = "Object Attributes"
common = false
required = false
examples = [ "authenticated-read" ]
description = "Canned ACL to apply to the created objects. For more information, see [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl)."

[sinks.aws_s3.options.grant_full_control]
type = "string"
category = "Object Attributes"
common = false
required = false
description = "Gives the named grantee READ, READ_ACP, and WRITE_ACP permissions on the created objects."

[sinks.aws_s3.options.grant_read]
type = "string"
category = "Object Attributes"
common = false
required = false
description = "Allows the named grantee to read the created objects and their metadata."

[sinks.aws_s3.options.grant_read_acp]
type = "string"
category = "Object Attributes"
common = false
required = false
description = "Allows the named grantee to read the created objects' ACL."

[sinks.aws_s3.options.grant_write_acp]
type = "string"
category = "Object Attributes"
common = false
required = false
description = "Allows the named grantee to write the created objects' ACL."

[sinks.aws_s3.options.server_side_encryption]
type = "string"
category = "Object Attributes"
common = false
required = false
examples = [ "AES256", "aws:kms" ]
description = "The server-side encryption algorithm used when storing these objects."

[sinks.aws_s3.options.ssekms_key_id]
type = "string"
category = "Object Attributes"
common = false
required = false
description = """\
If `server_side_encryption` has the value `"aws.kms"`, this specifies \
the ID of the AWS Key Management Service (AWS KMS) symmetrical customer \
managed customer master key (CMK) that will used for the created \
objects. If not specified, Amazon S3 uses the AWS managed CMK in AWS to \
protect the data.\
"""

[sinks.aws_s3.options.storage_class]
type = "string"
category = "Object Attributes"
common = false
required = false
description = "The storage class for the created objects. See [the S3 Storage Classes](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html) for more details."

[sinks.aws_s3.options.tags]
type = "table"
category = "Object Attributes"
common = false
required = false
description = "The tag-set for the object."

[sinks.aws_s3.options.tags.options."`[tag-name]`"]
type = "string"
required = false
examples = [ {"Tag1" = "Value1"} ]
description = "A custom tag to be added to the created objects."
