[sinks.socket]
title = "Socket"
buffer = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
write_to_description = "a socket, such as a TCP or Unix socket"
tls_options = ["+enabled"]

[sinks.socket.options.mode]
type = "string"
common = true
examples = ["tcp"]
null = false
description = """What type of socket to use.  Currently only "tcp" is valid."""

[sinks.socket.options.address]
type = "string"
common = true
examples = ["92.12.333.224:5000"]
null = false
description = "The TCP address."