version: '3'

services:
  mock-ec2-metadata:
    image: docker.io/timberiodev/mock-ec2-metadata:${AWS_VERSION}
  mock-localstack:
    image: docker.io/localstack/localstack-full:0.11.6
    environment:
    - SERVICES=kinesis,s3,cloudwatch,elasticsearch,es,firehose,sqs
  mock-watchlogs:
    image: docker.io/luciofranco/mockwatchlogs:latest
  mock-ecs:
    image: docker.io/amazon/amazon-ecs-local-container-endpoints:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $HOME/.aws/:/home/.aws/

networks:
  default:
    name: ${VECTOR_NETWORK}
    external: true
