version: 2

release-job-defaults: &release-job-defaults
  resource_class: large
  docker:
    - image: liuchong/rustup
  steps:
    - setup_remote_docker
    - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
    - run:
        name: Install Cross
        command: |
          apt-get update
          apt-get install -y git
          git clone https://github.com/rust-embedded/cross 
          cd cross
          cargo build --release
          ls target/x86_64-unknown-linux-musl -la
          mv target/release/cross /usr/bin
          cd ..
          rm -rf cross
    - checkout
    - run:
        name: Cross Compile
        command: cross build --target $TARGET build --release $EXTRA_ARGS

jobs:
  rustfmt:
    docker:
      - image: rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

  build-stable:
    resource_class: large
    docker:
      - image: rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install make and friends
          command: |
            apt-get update
            apt-get -y install build-essential
      - run:
          name: Build
          environment:
            RUSTFLAGS: "-D warnings"
          command: |
            cargo check --all --all-features --all-targets
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

  test-stable:
    resource_class: large
    docker:
      - image: rust:latest
        environment:
          RUST_BACKTRACE: full
          AWS_ACCESS_KEY_ID: "fake-aws-key"
          AWS_SECRET_ACCESS_KEY: "fake-aws-key"
      - image: localstack/localstack:latest
        environment:
          DATA_DIR: /tmp/localstack/data
          DEBUG: 1
          PORT_WEB_UI: 8888
          SERVICES: kinesis
      - image: minio/minio
        environment:
          MINIO_ACCESS_KEY: "test-access-key"
          MINIO_SECRET_KEY: "test-secret-key"
        command: server /tmp
      - image: luciofranco/mockwatchlogs:latest
      - image: spotify/kafka
        environment:
          ADVERTISED_HOST: localhost
          ADVERTISED_PORT: 9092
      - image: timberio/splunk-hec-test:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install make and friends
          command: |
            apt-get update
            apt-get -y install build-essential
      - run:
          name: Test
          command: |
            cargo test --all --features docker
      - store_test_results:
          path: ./test-results
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  release-arm:
    <<: *release-job-defaults
    environment:
      TARGET: "arm-unknown-linux-gnueabi"
      EXTRA_ARGS: --no-default-features

workflows:
  version: 2

  test:
    jobs:
      - rustfmt
      - build-stable
      - test-stable
      - release-arm
