#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs/
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
# enabled = true
# address = "127.0.0.1:8686"

# Dummy Apache formatted logs
[sources.dummy_logs]
type = "generator"
format = "syslog"
interval = 1

# Parse Syslog logs
# See the Remap reference: https://vector.dev/docs/reference/vrl/
[transforms.parse_logs]
type = "remap"
inputs = ["dummy_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

# Host-level metrics (CPU, memory, disk, etc)
#[sources.host_metrics]
#type = "host_metrics"

# Vector's own internal metrics
#[sources.internal_metrics]
#type = "internal_metrics"

# Print out parsed logs
[sinks.print]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
