# Platforms
#
# Platforms represent higher level abstractions. They are opinionated platforms
# where Vector can be installed.

[installation.platforms.docker]
title = "Docker"
archs = ["x86_64", "ARM64", "ARMv7"]
description = """\
[Docker][urls.docker] is an open platform for developing, shipping, and running
applications and services. Docker enables you to separate your services from \
your infrastructure so you can ship quickly. With Docker, you can manage your \
infrastructure in the same ways you manage your services. By taking advantage \
of Docker’s methodologies for shipping, testing, and deploying code quickly, \
you can significantly reduce the delay between writing code and running it in \
production.\
"""
interfaces = [
  "docker-cli",
  "docker-compose",
]
oss = ["Linux", "MacOS"]
strategies = [
  {name = "daemon", source = "docker"},
  {name = "sidecar", source = "file"},
  {name = "service", source = "vector"},
]
