
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api
    targetPort: api
    port: {{ .Values.service.port }}
    protocol: TCP
  {{- if .Values.service.metrics.enabled }}
  - name: metrics
    targetPort: {{ .Values.service.metrics.port }}
    protocol: TCP
    port: {{ .Values.service.metrics.port }}
  {{- end }}
  selector:
    {{- include "libvector.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.topologyKeys }}
  topologyKeys:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
