{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.service.metrics.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "libvector.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
{{- end }}
