[installation]
containers = [
  {name = "Docker", id = "docker"}
]
operating_systems = [
  {name = "Amazon Linux", id = "amazon-linux"},
  {name = "CentOS", id = "centos"},
  {name = "Debian", id = "debian"},
  {name = "MacOS", id = "macos"},
  {name = "Raspberry Pi", id = "raspberry-pi"},
  {name = "RHEL", id = "rhel"},
  {name = "Ubuntu", id = "ubuntu"},
  {name = "Windows", id = "windows"}
]
package_managers = [
  {name = "DPKG", id = "dpkg"},
  {name = "Homebrew", id = "homebrew"},
  {name = "RPM", id = "rpm"},
]

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
name = "Linux (x86_64)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-aarch64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
name = "Linux (ARM64)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armv7-unknown-linux-musleabihf.tar.gz"
file_type = "tar.gz"
name = "Linux (ARMv7)"
os = "Linux"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-apple-darwin.tar.gz"
file_type = "tar.gz"
name = "MacOS (x86_64)"
os = "MacOS"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-pc-windows-msvc.zip"
file_type = "zip"
name = "Windows (x86_64, 7+)"
os = "Windows"
type = "archive"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-amd64.deb"
file_type = "deb"
name = "Deb (x86_64)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-arm64.deb"
file_type = "deb"
name = "Deb (ARM64)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armhf.deb"
file_type = "deb"
name = "Deb (ARMv7)"
os = "Linux"
package_manager = "DPKG"
type = "package"

[[installation.downloads]]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64.rpm"
file_type = "rpm"
name = "RPM (x86_64)"
os = "Linux"
package_manager = "RPM"
type = "package"