{{ if .Values.haproxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libvector.fullname" . }}-haproxy
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
spec:
  replicas: {{ .Values.haproxy.replicas }}
  selector:
    matchLabels:
      {{- include "libvector.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: load-balancer
  template:
    metadata:
      annotations:
        {{- with .Values.haproxy.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.haproxy.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "libvector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: load-balancer
    spec:
      {{- include "libvector.imagePullSecrets" . | indent 6 }}
      securityContext:
        {{- toYaml .Values.haproxy.podSecurityContext | nindent 8 }}
      {{- if .Values.haproxy.podPriorityClassName }}
      priorityClassName: {{ .Values.haproxy.podPriorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "libvector.fullname" . }}-haproxy
      containers:
        - name: haproxy
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          image: "{{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}"
          imagePullPolicy: "{{ .Values.haproxy.image.pullPolicy }}"
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/
              readOnly: true
      {{- with .Values.haproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "libvector.fullname" . }}-haproxy
{{- end }}
