{{ if .Values.haproxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: vector
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
spec:
  selector:
    {{- include "libvector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
  ports:
  - name: datadog
    port: 3837
    protocol: TCP
    targetPort: 3837
  - name: metrics
    port: 1024
    protocol: TCP
    targetPort: 1024
  - name: syslog
    port: 5140
    protocol: TCP
    targetPort: 5140
  - name: vector
    port: 9000
    protocol: TCP
    targetPort: 9000
{{- end }}
