{{ if .Values.haproxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "libvector.fullname" . }}-haproxy
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
  {{- include "vector-aggregator.servicePorts" . | nindent 2 }}
  - name: metrics
    port: 1024
    protocol: TCP
    targetPort: 1024
  selector:
    {{- include "libvector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
{{- end }}
