{{ if .Values.haproxy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "libvector.fullname" . }}-haproxy
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-balancer
{{- end }}
