services:
  mock-ec2-metadata:
    image: timberiodev/mock-ec2-metadata:latest
    networks:
      - backend

  mock-localstack:
    image: localstack/localstack-full:0.11.6
    environment:
      - SERVICES=kinesis,s3,cloudwatch,elasticsearch,es,firehose,sqs
    networks:
      - backend

  mock-watchlogs:
    image: luciofranco/mockwatchlogs:latest
    networks:
      - backend

  mock-ecs:
    image: amazon/amazon-ecs-local-container-endpoints:latest
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "test"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "aws-integration-tests"
      - "--lib"
      - "${FILTER:-::aws_}"
      - "--"
      - "--nocapture"
    depends_on:
      - mock-ec2-metadata
      - mock-localstack
      - mock-watchlogs
      - mock-ecs
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - EC2_METADATA_ADDRESS=http://mock-ec2-metadata:8111
      - SQS_ADDRESS=http://mock-localstack:4566
      - WATCHLOGS_ADDRESS=http://mock-watchlogs:6000
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend
    volumes:
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - ${PWD}:/code

# this is made to improve the build when running locally
volumes:
  cargogit: {}
  cargoregistry: {}

networks:
  backend: {}

