image:
  # Use the latest release image.
  version: latest

env:
  # Set the log level reasonably high.
  - name: VECTOR_LOG
    value: info

extraConfigDirSources:
  - configMap:
      name: vector-aggregator-config
      optional: true
  - secret:
      name: vector-aggregator-config
      optional: true
