# Component Features - Linux
#
# Validates that each component feature compiles
#
# Runs on:
#  - scheduled UTC midnight Tues-Sat
#  - on PR comment (see comment-trigger.yml)
#  - on demand from github actions UI

name: Component Features - Linux

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    # At midnight UTC Tue-Sat
    - cron: '0 0 * * 2-6'

jobs:
  check-component-features-schedule:
    # use free tier on the schedule
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make check-component-features

  check-component-features-comment:
    # expedite results when running on demand
    runs-on: [linux, ubuntu-20.04-8core]
    if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
    steps:
      - name: (PR comment) Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: (PR comment) Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Component Features - Linux
          status: pending

      - name: (PR comment) Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          submodules: "recursive"

      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make check-component-features

      - name: (PR comment) Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Component Features - Linux
          status: ${{ job.status }}
