name: ga-test

on:
  workflow_dispatch:

env:
  AUTOINSTALL: true
  CHANNEL: nightly
  VERBOSE: true
  CI: true

jobs:
  build-x86_64-unknown-linux-musl-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          PASS_FEATURES: "default-cmake"
        run: make package-x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v1
        with:
          path: "./target/artifacts/vector-x86_64-unknown-linux-musl.tar.gz"

  build-x86_64-unknown-linux-gnu-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          PASS_FEATURES: "default"
        run: make package-x86_64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          path: "./target/artifacts/vector-x86_64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          path: "./target/artifacts/vector-*amd64.deb"
      - uses: actions/upload-artifact@v1
        with:
          path: "./target/artifacts/vector-*x86_64.rpm"
