name: generate

on:
  push:
    branches:
      - master
    paths:
      - "**/*.md.erb"
      - ".meta/**"
      - "scripts/generate.rb"
      - "scripts/generate/**"

  pull_request:
    paths:
      - "**/*.md.erb"
      - ".meta/**"
      - "scripts/generate.rb"
      - "scripts/generate/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make check-generate
