name: Update install.sh Suite

on:
  workflow_call:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:

  sync-install:
    runs-on: ubuntu-20.04
    if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && contains(github.evemt.comment.body, '/ci-run-all'))
    steps:
      - name: Validate issue comment
        if: github.event_name == 'issue_comment'
        uses: tspascoal/get-user-teams-membership@v2
        with:
          username: ${{ github.actor }}
          team: 'Vector'
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}

      - uses: actions/checkout@v3
      - run: pip3 install awscli --upgrade --user
      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.CI_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}"
        run: make sync-install

  test-install:
    needs: sync-install
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install --yes curl bc
      - run:  curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash -s -- -y
      - run: ~/.vector/bin/vector --version
