# Integration Test Suite
#
# This workflow runs the integration tests. If the workflow is triggered in the merge queue, all integration tests
# are run. If the workflow is triggered in a PR commit, then the files changed in the PR are evaluated to determine
# if any integration tests will run.

name: Integration Test Suite

on:
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  # `github.event.number` exists for pull requests, otherwise fall back to SHA for merge queue
  group: ${{ github.workflow }}-${{ github.event.number || github.event.merge_group.head_sha }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  TEST_DATADOG_API_KEY: ${{ secrets.CI_TEST_DATADOG_API_KEY }}
  TEST_APPSIGNAL_PUSH_API_KEY: ${{ secrets.TEST_APPSIGNAL_PUSH_API_KEY }}
  AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug
  # observing issues fetching boringssl via HTTPS in the OSX build, seeing if this helps
  # can be removed when we switch back to the upstream openssl-sys crate
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:

  changes:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/changes.yml
    with:
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref  }}
      source: false
      int_tests: true
    secrets: inherit

  integration-tests:
    name: Integration Tests
    runs-on: [linux, ubuntu-20.04-4core]
    needs: changes
    if: always() && (
      github.event_name == 'merge_group' || (
          needs.changes.outputs.all-int == 'true'
            || needs.changes.outputs.amqp == 'true'
            || needs.changes.outputs.appsignal == 'true'
            || needs.changes.outputs.aws == 'true'
            || needs.changes.outputs.axiom == 'true'
            || needs.changes.outputs.azure == 'true'
            || needs.changes.outputs.clickhouse == 'true'
            || needs.changes.outputs.databend == 'true'
            || needs.changes.outputs.datadog == 'true'
            || needs.changes.outputs.dnstap == 'true'
            || needs.changes.outputs.docker-logs == 'true'
            || needs.changes.outputs.elasticsearch == 'true'
            || needs.changes.outputs.eventstoredb == 'true'
            || needs.changes.outputs.fluent == 'true'
            || needs.changes.outputs.gcp == 'true'
            || needs.changes.outputs.humio == 'true'
            || needs.changes.outputs.http-client == 'true'
            || needs.changes.outputs.influxdb == 'true'
            || needs.changes.outputs.kafka == 'true'
            || needs.changes.outputs.logstash == 'true'
            || needs.changes.outputs.loki == 'true'
            || needs.changes.outputs.mongodb == 'true'
            || needs.changes.outputs.nats == 'true'
            || needs.changes.outputs.nginx == 'true'
            || needs.changes.outputs.opentelemetry == 'true'
            || needs.changes.outputs.postgres == 'true'
            || needs.changes.outputs.prometheus == 'true'
            || needs.changes.outputs.pulsar == 'true'
            || needs.changes.outputs.redis == 'true'
            || needs.changes.outputs.splunk == 'true'
            || needs.changes.outputs.webhdfs == 'true'
        )
      )
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - run: sudo npm -g install @datadog/datadog-ci

      - run: docker image prune -af ; docker container prune -f

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.amqp == 'true' }}
        name: amqp
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh amqp

      # Due to https://github.com/nick-fields/retry/issues/54 , we cannot use the retry GHA with uploading the test
      # results to DD, because it requires the env var to be passed in. So we must do that in a separate step.
      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.appsignal == 'true' }}
        name: appsignal
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  appsignal

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.aws == 'true' }}
        name: aws
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  aws

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.axiom == 'true' }}
        name: axiom
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  axiom

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.azure == 'true' }}
        name: azure
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  azure

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.clickhouse == 'true' }}
        name: clickhouse
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  clickhouse

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.databend == 'true' }}
        name: databend
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  databend

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.datadog == 'true' }}
        name: datadog-agent
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  datadog-agent

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.datadog == 'true' }}
        name: datadog-logs
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  datadog-logs

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.datadog == 'true' }}
        name: datadog-metrics
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  datadog-metrics

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.datadog == 'true' }}
        name: datadog-traces
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  datadog-traces

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.dnstap == 'true' }}
        name: dnstap
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  dnstap

      - run: ./scripts/upload-test-results.sh

      - run: docker image prune -af --filter=label!=vector-test-runner=true ; docker container prune -f

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.docker-logs == 'true' }}
        name: docker-logs
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  docker-logs

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.elasticsearch == 'true' }}
        name: elasticsearch
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  elasticsearch

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.eventstoredb == 'true' }}
        name: eventstoredb
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  eventstoredb

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.fluent == 'true' }}
        name: fluent
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  fluent

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.gcp == 'true' }}
        name: gcp
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  gcp

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.humio == 'true' }}
        name: humio
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  humio

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.http-client == 'true' }}
        name: http-client
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  http-client

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.influxdb == 'true' }}
        name: influxdb
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  influxdb

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.kafka == 'true' }}
        name: kafka
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  kafka

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.logstash == 'true' }}
        name: logstash
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  logstash

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.loki == 'true' }}
        name: loki
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  loki

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.mongodb == 'true' }}
        name: mongodb
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  mongodb

      - run: ./scripts/upload-test-results.sh

      - run: docker image prune -af --filter=label!=vector-test-runner=true ; docker container prune -f

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.nats == 'true' }}
        name: nats
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  nats

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.nginx == 'true' }}
        name: nginx
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  nginx

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.opentelemetry == 'true' }}
        name: opentelemetry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  opentelemetry

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.postgres == 'true' }}
        name: postgres
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  postgres

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.prometheus == 'true' }}
        name: prometheus
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  prometheus

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.pulsar == 'true' }}
        name: pulsar
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  pulsar

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.redis == 'true' }}
        name: redis
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  redis

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' }}
        name: shutdown
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  shutdown

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.splunk == 'true' }}
        name: splunk
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  splunk

      - run: ./scripts/upload-test-results.sh

      - if: ${{ github.event_name == 'merge_group' || needs.changes.outputs.all-int == 'true' || needs.changes.outputs.webhdfs == 'true' }}
        name: webhdfs
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: scripts/ci-integration-test.sh  webhdfs

      - run: ./scripts/upload-test-results.sh

  integration-test-suite:
    name: Integration Test Suite
    runs-on: ubuntu-latest
    if: always()
    needs:
      - integration-tests
    env:
      FAILED: ${{ contains(needs.*.result, 'failure') }}
    steps:
      - run: |
          echo "failed=${{ env.FAILED }}"
          if [[ "$FAILED" == "true" ]] ; then
            exit 1
          else
            exit 0
          fi
