name: linting
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: .markdownlintrc
