name: website

on:
  push:
    branches:
      - master
    paths:
      - "**/*.md"

  pull_request:
    paths:
      - "**/*.md"

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - run: make check-markdown
