name: nightly
on:
  push:
    branches:
      - master
  pull_request: {}

# on:
#   schedule:
#     - cron:  "0 14 * * *"

jobs:
  build-x86_64-unknown-linux-musl-archive-and-deb-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./scripts/docker-run.sh builder-x86_64-unknown-linux-musl make build-archive package-deb
        env:
          PASS_FEATURES: "default-musl"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-unknown-linux-musl.tar.gz"
          path: "./target/artifacts/vector-x86_64-unknown-linux-musl.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: "vector-x86_64-unknown-linux-musl.tar.gz"
          path: "./target/artifacts/vector-x86_64-unknown-linux-musl.tar.gz"
