name: Call Build Preview

on:
  pull_request:
    types: [opened, reopened, syncronize]

jobs:
  approval_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approval
        run: |
          echo "Workflow has been allowed to run for PR ${{ github.event.number }}"

